name: belah_duren
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0
  otp_text_field: ^1.0.2
  flutter_search_bar: ^2.1.0
  dio: ^3.0.10
  shared_preferences: ^0.5.12+4
  flutter_barcode_scanner: ^1.0.2
  intl: ^0.16.1
  geolocator: ^6.2.0
  datetime_picker_formfield: ^1.0.0
  image_picker: ^0.6.7+22
  google_maps_flutter: ^1.2.0
  webview_flutter: ^1.0.7
  modal_progress_hud: ^0.1.3
  firebase_messaging: ^8.0.0-dev.15
  flutter_local_notifications: ^4.0.1+2
  qr_flutter: ^4.0.0
  url_launcher: ^6.0.3
#  flutter_launcher_icons: ^0.9.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

#flutter_icons:
#  android: false
#  ios: true
#  image_path: "assets/images/logoios.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/icon_poin.png
    - assets/images/arrow_kanan.png
    - assets/images/banner_about.png
    - assets/images/box_menu.png
    - assets/images/box_poin.png
    - assets/images/box_promotion.png
    - assets/images/delivery.png
    - assets/images/event_code.png
    - assets/images/home_off.png
    - assets/images/home_on.png
    - assets/images/inbox_off.png
    - assets/images/inbox_on.png
    - assets/images/logo_home.png
    - assets/images/pickup.png
    - assets/images/profile_off.png
    - assets/images/profile_on.png
    - assets/images/promotion.png
    - assets/images/scanqr.png
    - assets/images/slide_utama_home.png
    - assets/images/shop_off.png
    - assets/images/shop_on.png
    - assets/images/banner.png
    - assets/images/combo.png
    - assets/images/delivery_on.png
    - assets/images/edit_profile.png
    - assets/images/history_transaksi.png
    - assets/images/icon_bronze_off.png
    - assets/images/icon_bronze_on.png
    - assets/images/icon_gold_off.png
    - assets/images/icon_gold_on.png
    - assets/images/icon_platinum_off.png
    - assets/images/icon_platinum_on.png
    - assets/images/icon_silver_off.png
    - assets/images/icon_silver_on.png
    - assets/images/keranjang.png
    - assets/images/ketentuan_layanan.png
    - assets/images/logo.png
    - assets/images/logout.png
    - assets/images/pickup_on.png
    - assets/images/pin.png
    - assets/images/smile.png
    - assets/images/background.png
    - assets/images/header_home.png
    - assets/images/pickup_icon.jpg
    - assets/images/scan_qr.png
    - assets/images/user.png
    - assets/images/empty_history.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
